apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: banksystem-web-ingress
  namespace: banksystem
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/certificate-arn: <CERTIFICATE_ARN>
    alb.ingress.kubernetes.io/ssl-redirect: '443'
spec:
  rules:
  - host: banksystem.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: banksystem-web-service
            port:
              number: 80
